baseURL = 'https://voluble-souffle-995141.netlify.app/'
languageCode = 'en-us'
title = 'My New Hugo Site'
paginate = '1'
paginatePath = ''
theme = 'gallery'


[taxonomies]
  category = "categories"

[outputs]
    home = [ "HTML", "JSON", "RSS"]

