[backend]
  name = "git-gateway"
  branch = "main" # Branch to update (optional; defaults to master)
  repo = "davewibisono/catalyst-neuro"

[media_folder]
  path = "static/assets/img"

[public_folder]
  path = "/img"

[[collections]]
  name = 'blog'
  label = 'Blog'
  folder = 'content/blog'
  create = true
  slug = '{{year}}-{{month}}-{{day}}-{{slug}}'

  [collections.editor]
    preview = false

  [[collections.fields]]
    label = 'Title'
    name = 'title'
    widget = 'string'

  [[collections.fields]]
    label = 'Publish Date'
    name = 'date'
    widget = 'datetime'

  [[collections.fields]]
    label = 'Description'
    name = 'description'
    widget = 'string'

  [[collections.fields]]
    label = 'Body'
    name = 'body'
    widget = 'markdown'
