backend:
  name: git-gateway
  branch: main
media_folder: static/assets/img
public_folder: assets/img
collections:
  - name: 'blog_single'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'blog_single' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Content', name: 'body', widget: 'markdown' }
      - { label: 'Type', name: 'type', widget: 'select', options: ['featured', 'other'], default: 'other' }

  - name: 'portfolio'
    label: 'Portfolio'
    folder: 'content/portfolio'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Tag Bar', name: 'tag_bar', widget: 'string' }
      - { label: 'Subtitle', name: 'sub_title', widget: 'string' }
      - { label: 'Description', name: 'description', widget: 'text' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'ID', name: 'id', widget: 'string' }
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'portfolio' }
      - { label: 'Weight', name: 'weight', widget: 'number' }

  - name: "pages"
    label: "Pages"
    files:
      - file: "data/home.yml"
        label: "Home"
        name: "home"
        fields:
          - { label: 'Hero Heading', name: 'hero_heading', widget: 'string' }
          - { label: 'Hero Paragraph', name: 'hero_paragraph', widget: 'text' }
          - { label: 'Hero Image', name: 'hero_image', widget: 'image' }
          - { label: 'Mission Heading', name: 'mission_heading', widget: 'string' }
          - { label: 'Mission Paragraph 1', name: 'mission_paragraph_1', widget: 'text' }
          - { label: 'Mission Paragraph 2', name: 'mission_paragraph_2', widget: 'text' }
          - { label: 'Mission Image', name: 'mission_image', widget: 'image' }
          - { label: 'Software Heading', name: 'software_heading', widget: 'string' }
          - { label: 'Software Paragraph 1', name: 'software_paragraph_1', widget: 'text' }
          - { label: 'Software Paragraph 2', name: 'software_paragraph_2', widget: 'text' }
          - { label: 'Software Paragraph 3', name: 'software_paragraph_3', widget: 'text' }
          - { label: 'Software Image', name: 'software_image', widget: 'image' }
          - { label: 'Clients Heading', name: 'clients_heading', widget: 'string' }
          - { label: 'Clients Paragraph', name: 'clients_paragraph', widget: 'text' }
          - { label: 'CTA Heading', name: 'cta_heading', widget: 'string' }
          - { label: 'CTA Paragraph', name: 'cta_paragraph', widget: 'text' }
          - { label: 'CTA Image', name: 'cta_image', widget: 'image' }
      - file: "data/mission.yml"
        label: "Mission"
        name: "mission"
        fields:
        - { label: 'Main Heading', name: 'main_heading', widget: 'string' }
        - { label: 'Card Image', name: 'card_image', widget: 'image' }
        - { label: 'Card Paragraph 1', name: 'card_paragraph_1', widget: 'text' }
        - { label: 'Card Paragraph 2', name: 'card_paragraph_2', widget: 'text' }

      - file: "data/software.yml"
        label: "Software"
        name: "software"
        fields:
        - { label: 'Main Heading', name: 'main_heading', widget: 'string' }
        - { label: 'Card Image', name: 'card_image', widget: 'image' }
        - { label: 'Card Paragraph', name: 'card_paragraph', widget: 'text' }
        - { label: 'Dropdown 1', name: 'dropdown_1', widget: 'string' }
        - { label: 'FAQ 1 Heading', name: 'faq_1_heading', widget: 'string' }
        - { label: 'FAQ 1 Paragraph 1', name: 'faq_1_paragraph_1', widget: 'text' }
        - { label: 'FAQ 1 Paragraph 2', name: 'faq_1_paragraph_2', widget: 'text' }
        - { label: 'FAQ 1 Paragraph 3', name: 'faq_1_paragraph_3', widget: 'text' }
        - { label: 'FAQ 1 Image', name: 'faq_1_image', widget: 'image' }
        - { label: 'Dropdown 2', name: 'dropdown_2', widget: 'string' }
        - { label: 'FAQ 2 Heading', name: 'faq_2_heading', widget: 'string' }
        - { label: 'FAQ 2 Paragraph 1', name: 'faq_2_paragraph_1', widget: 'text' }
        - { label: 'FAQ 2 Paragraph 2', name: 'faq_2_paragraph_2', widget: 'text' }
        - { label: 'FAQ 2 Paragraph 3', name: 'faq_2_paragraph_3', widget: 'text' }
        - { label: 'FAQ 2 Image', name: 'faq_2_image', widget: 'image' }
        - { label: 'Dropdown 3', name: 'dropdown_3', widget: 'string' }
        - { label: 'FAQ 3 Heading', name: 'faq_3_heading', widget: 'string' }
        - { label: 'FAQ 3 Paragraph 1', name: 'faq_3_paragraph_1', widget: 'text' }
        - { label: 'FAQ 3 Paragraph 2', name: 'faq_3_paragraph_2', widget: 'text' }
        - { label: 'FAQ 3 Paragraph 3', name: 'faq_3_paragraph_3', widget: 'text' }
        - { label: 'FAQ 3 Image', name: 'faq_3_image', widget: 'image' }
        - { label: 'Dropdown 4', name: 'dropdown_4', widget: 'string' }
        - { label: 'FAQ 4 Heading', name: 'faq_4_heading', widget: 'string' }
        - { label: 'FAQ 4 Paragraph 1', name: 'faq_4_paragraph_1', widget: 'text' }
        - { label: 'FAQ 4 Paragraph 2', name: 'faq_4_paragraph_2', widget: 'text' }
        - { label: 'FAQ 4 Paragraph 3', name: 'faq_4_paragraph_3', widget: 'text' }
        - { label: 'FAQ 4 Image', name: 'faq_4_image', widget: 'image' }